CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(150) NOT NULL COLLATE utf8mb4_unicode_ci,
    password VARCHAR(255) NOT NULL,
    profile ENUM('USER', 'ADMIN', 'MODERATOR') NOT NULL DEFAULT 'USER',
    active BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE=InnoDB;